### ISSUE TITLE
Créer une page github

### ISSUE THREAD

**Issue by YoannDupont** [Sazuna/PPE1#1]
Bonjour,

Il faudrait créer une page github pour votre projet. Vous semblez proches d'avoir des tableaux, cela permettra de tester en conditions réelles.

**Comment by Sazuna** [comment]
Bonjour,

Page github créée. Tableaux pas encore générés. Nous nous en occuperons rapidement.

**Comment by Sazuna** [comment]
Bonjour Monsieur,

Page github créée. Tableaux pas encore générés. Nous nous en occuperons rapidement.

Cordialement,
Liza FRETEL

**Comment by YoannDupont** [comment]
Bonjour,

Très bien. Le site étant créé, je clos l'issue.

Cordialement.
